### PR TITLE
Create social_media_accounts

### PR DESCRIPTION
**Pull request by theHam97**
The handles for the Demodam social media accounts

### CODE REVIEW

**Comment by Ainali** [comment]
Should we not just add this to the README instead?

**Comment by theHam97** [comment]
> Should we not just add this to the README instead?

Depends on what the purpose is of mentioning the handles in the repo. If it is only as a footnote for the developers, a separate file is probably enough. If it would serve any function more formal, then adding it to the README would makes sense to me.

**Comment by Ainali** [comment]
Ok, let's start with this as just a piece of doumentation.

**Comment by Ainali** [comment]
By the way, what does the cg stand for?

**Comment by theHam97** [comment]
> By the way, what does the cg stand for?

cg = common ground

**Pull request merged**
